name: client-frontend
# TODO: Use repository secrets for required environment variables and amplify setup
on:
  push:
    paths:
      - ".github/workflows/client-frontend.yaml"
      - "src/**"
      - "nginx/**"
      - "public/**"
      - "amplify/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "Dockerfile"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Amplify setup
        run: |
          cat > ./src/aws-exports.js <<EOF
          const awsmobile = {
            "aws_project_region": "eu-central-1"
          };
          export default awsmobile;
          EOF
      - name: Environment setup
        run: |
          cat > .env <<EOF
          REACT_APP_USER_POOL_ID=
          REACT_APP_USER_POOL_CLIENT_ID=
          REACT_APP_BACKEND=https://api-dev.devpie.io/api
          EOF
      - name: Build and Push Image
        env:
          IMAGE: client
          OWNER: ${{ github.repository_owner }}
        run: |
          export SHA=$(git rev-parse --short HEAD)
          
          docker build --tag ghcr.io/$OWNER/$IMAGE:$SHA .
          docker push ghcr.io/$OWNER/$IMAGE:$SHA

          echo $OWNER/$IMAGE:$SHA > .build-version

          cat > patch.sh <<EOF
          #!/bin/bash
          sed -i 's/$IMAGE:.*/$IMAGE:$SHA/' ./main/manifests/$IMAGE-frontend.yaml
          EOF

          chmod +x patch.sh

      - uses: actions/checkout@v2
        with:
          repository: devpies/saas-infra
          token: ${{ secrets.PAT }}
          path: main
      - run: |
          ./patch.sh
          export VERSION=$(cat .build-version)

          cd main
          git config --local user.email github-actions@github.com
          git config --local user.name github-actions
          git add .
          git commit -m "new release: $VERSION"
          git push